require("monokai").setup({ palette = require("monokai").pro })
require("after.lsp")
require("after.tree-sitter")
require("after.transparent")
require("after.nvim-tree")
require("after.telescope")
require("after.whichkey")
require("lualine").setup()
